export enum Activities {
    codeReviews = "Code reviews",
    mentoring = "Mentoring",
    pairing = "Pairing",
    tdd = "Test Driven Development",
    presenting = "Presentations",
    htmlAndCSS = "Developing sites according to HTML specification and styling with CSS",
    spaDevelopmentWithAngularJs = "Spa development with angular js",
    reactiveProgrammingWithRedux = "Reactive programming with redux",
    spaDevelopmentWithReact = "Spa development with react",
    preformanceTuningJavascript = "Preformance tuning javascript",
    preformanceTuningSqlQueriesAndReports = "Preformance tuning sql queries and reports",
    configuringBuildScriptsAndBuildServers = "Configuring build scripts and build servers",
    supportingProductionApplications = "Supporting production applications",
    javaMicroServiceDevelopmentWithSpringBoot1_4 = "Java micro service development with spring boot1 4",
    automatedRestApiTestingJavaMicroServicesAndJava8 = "Automated rest api testing java micro services and java8",
    automatedRestApiTestingJavaMicroServices = "Automated rest api testing java micro services",
    configuringAwsInstances = "Configuring aws instances",
    serverSideRenderingWithPhantomJsAndElectron = "Server side rendering with phantom js and electron",
    debuggingJavaScriptApplications = "Debugging java script applications",
    versionControlWithGit = "Version control with git",
    versionControlWithTfs = "Version control with tfs",
    versionControlWithSvn = "Version control with svn",
    developingJavaScriptApplications = "Developing java script applications",
    developingAndModifyingStoredProcedures = "Developing and modifying stored procedures",
}
